KEY_OVERRIDE_ENABLE ?= yes
TAP_DANCE_ENABLE ?= yes
COMBO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
CAPS_WORD_ENABLE ?= yes
NKRO_ENABLE ?= yes

LTO_ENABLE ?= no
AUTOCORRECT_ENABLE ?= no
CONSOLE_ENABLE ?= no
GRAVE_ESC_ENABLE ?= no
LAYER_LOCK_ENABLE ?= no
SPACE_CADET_ENABLE ?= no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
BOOTMAGIC_ENABLE ?= no
